[build-system]
requires = [
    "scikit-build-core>=1.0.3",
    "pybind11>=3.0.4"
]
build-backend = "scikit_build_core.build"

[project]
name = "nn-engine-core"
version = "0.1.8"
description = "A high-performance C++ parametric optimization backend for NNEngine"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"

authors = [
    { name = "Youssef Mohamed" }
]

dependencies = [
    "numpy>=2.5.1"
]
keywords = ["machine-learning", "neural-networks", "autograd", "c++", "eigen"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Typing :: Typed"
]

[project.urls]
Homepage = "https://github.com/MLEngineProject/NNEngine"
Tracker = "https://github.com/MLEngineProject/NNEngine/issues"

[tool.scikit-build]
cmake.version = ">=4.4.0"
wheel.install-dir = "."
build-dir = "build/{wheel_tag}"
wheel.packages = ["nnengine"]

[tool.cibuildwheel]
skip = "*-musllinux_* *-win32 *i686 cp*t-win*"

test-requires = ["pytest", "numpy"]
test-command = "pytest {project}/tests/python"