"""
C++ Core Backend Engine for NNEngine
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Adam', 'AdamW', 'BatchNorm1dLayer', 'Conv2dLayer', 'DataLoader', 'DenseLayer', 'DropoutLayer', 'JITGraph', 'L2Regularizer', 'Layer', 'LeakyReLULayer', 'Loss', 'MSELoss', 'Module', 'Op', 'Optimizer', 'ReLULayer', 'Regularizer', 'SGD', 'Scheduler', 'SoftmaxCrossEntropyLoss', 'StepLR', 'Tape', 'Tensor', 'set_seed']
class Adam(Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513) -> None:
        ...
class AdamW(Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513, weight_decay: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582) -> None:
        ...
class BatchNorm1dLayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self, num_features: typing.SupportsInt | typing.SupportsIndex, eps: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-06, momentum: typing.SupportsFloat | typing.SupportsIndex = 0.10000000149011612) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class Conv2dLayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self, in_channels: typing.SupportsInt | typing.SupportsIndex, out_channels: typing.SupportsInt | typing.SupportsIndex, in_h: typing.SupportsInt | typing.SupportsIndex, in_w: typing.SupportsInt | typing.SupportsIndex, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = 1, pad: typing.SupportsInt | typing.SupportsIndex = 0) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class DataLoader:
    def __init__(self, X: Tensor, y: Tensor, batch_size: typing.SupportsInt | typing.SupportsIndex, shuffle: bool = True, drop_last: bool = False) -> None:
        ...
    def has_next(self) -> bool:
        ...
    def next_batch(self, X_batch: Tensor, y_batch: Tensor) -> None:
        ...
    def reset(self) -> None:
        ...
class DenseLayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class DropoutLayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self, p: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class JITGraph:
    def __init__(self, model: Layer, optimizer: Optimizer, loss_fn: Loss, regularizer: Regularizer = None) -> None:
        ...
    def evaluate(self, dataloader: DataLoader) -> float:
        ...
    def fast_fit(self, dataloader: DataLoader, val_dataloader: DataLoader = None, epochs: typing.SupportsInt | typing.SupportsIndex, tol: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-05, n_iter_no_change: typing.SupportsInt | typing.SupportsIndex = 10, verbose: bool = True) -> None:
        ...
    def fast_loop(self, dataloader: DataLoader) -> tuple[float, int]:
        ...
    def load_checkpoint(self, base_filepath: str) -> None:
        ...
    def save_checkpoint(self, base_filepath: str) -> None:
        ...
    def set_scheduler(self, scheduler: Scheduler) -> None:
        ...
    def trace_batch(self, dataloader: DataLoader) -> float:
        ...
class L2Regularizer(Regularizer):
    def __init__(self, l2: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-05) -> None:
        ...
class Layer:
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def eval(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
    def train(self, mode: bool = True) -> None:
        ...
class LeakyReLULayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self, alpha: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class Loss:
    def backward(self) -> None:
        ...
    def forward(self, predictions: Tensor, targets: Tensor) -> float:
        ...
class MSELoss(Loss):
    def __init__(self) -> None:
        ...
class Module(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def load_weights(self, filepath: str) -> None:
        ...
    def named_parameters(self) -> dict[str, Tensor]:
        ...
    def parameters(self) -> list[Tensor]:
        ...
    def predict(self, X: Tensor) -> Tensor:
        ...
    def register_module(self, name: str, layer: Layer) -> Layer:
        ...
    def save_weights(self, filepath: str) -> None:
        ...
class Op:
    def __init__(self) -> None:
        ...
    def backward(self) -> None:
        ...
    def forward(self) -> None:
        ...
class Optimizer:
    def set_parameters(self, params: collections.abc.Sequence[Tensor]) -> None:
        ...
    def step(self) -> None:
        ...
    def zero_grad(self) -> None:
        ...
class ReLULayer(Layer):
    def __call__(self, arg0: Tensor) -> Tensor:
        ...
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class Regularizer:
    pass
class SGD(Optimizer):
    def __init__(self, learning_rate: typing.SupportsFloat | typing.SupportsIndex = 0.009999999776482582) -> None:
        ...
class Scheduler:
    pass
class SoftmaxCrossEntropyLoss(Loss):
    def __init__(self) -> None:
        ...
class StepLR(Scheduler):
    def __init__(self, optimizer: Optimizer, step_size: typing.SupportsInt | typing.SupportsIndex, gamma: typing.SupportsFloat | typing.SupportsIndex = 0.10000000149011612) -> None:
        ...
    def step(self) -> None:
        ...
class Tape:
    record_ops: bool
    def __enter__(self) -> Tape:
        ...
    def __exit__(self, arg0: typing.Any, arg1: typing.Any, arg2: typing.Any) -> None:
        ...
    def __init__(self, record_ops: bool = True) -> None:
        ...
    def alloc_tensor(self, shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], requires_grad: bool = True) -> Tensor:
        ...
    def backward(self) -> None:
        ...
    def push_tensor(self, data: Tensor, requires_grad: bool = True) -> Tensor:
        ...
    def record_op(self, op: Op) -> None:
        ...
    def reset(self) -> None:
        ...
class Tensor:
    requires_grad: bool
    def __buffer__(self, flags):
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
    def __init__(self, arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None:
        ...
    def __release_buffer__(self, buffer):
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
    def __repr__(self) -> str:
        ...
    @property
    def data(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    @property
    def grad(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    @property
    def shape(self) -> list[int]:
        ...
    @shape.setter
    def shape(self, arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
def set_seed(seed: typing.SupportsInt | typing.SupportsIndex) -> None:
    ...
