name: Build and Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # 1. Reuse the CI workflow to test and generate stubs!
  run_ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: write

  # 2. Build multi-OS wheels
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: run_ci
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Download generated stubs
        uses: actions/download-artifact@v8
        with:
          name: py-stubs
          path: nnengine/

      - name: Create ccache directory
        if: runner.os != 'Windows'
        run: mkdir -p .ccache

      - name: Cache ccache
        if: runner.os != 'Windows'
        uses: actions/cache@v6
        with:
          path: .ccache
          key: ccache-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ matrix.os }}-

      - name: Build and Test wheels
        uses: pypa/cibuildwheel@v4.1.1
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y ccache
          CIBW_BEFORE_ALL_MACOS: brew install libomp ccache
          CIBW_BUILD_FRONTEND: pip
          CIBW_ARCHS_MACOS: arm64
          CIBW_TEST_COMMAND: "python -c 'import nnengine as nne; print(nne._backend);'"

          CIBW_ENVIRONMENT_LINUX: >
            PATH="/usr/lib64/ccache:/usr/lib/ccache:$PATH"
            CMAKE_CXX_COMPILER_LAUNCHER=ccache
            CCACHE_DIR=/project/.ccache
            CCACHE_COMPILERCHECK=content

          CIBW_ENVIRONMENT_MACOS: >
            CMAKE_C_COMPILER_LAUNCHER=ccache
            CMAKE_CXX_COMPILER_LAUNCHER=ccache
            CCACHE_DIR=${{ github.workspace }}/.ccache
            CCACHE_COMPILERCHECK=content
            SKBUILD_CMAKE_ARGS="-DCMAKE_OSX_ARCHITECTURES=arm64"
            ARCHFLAGS="-arch arm64"
            MACOSX_DEPLOYMENT_TARGET="26.0"

      - name: Fix cache permissions for Docker
        if: runner.os == 'Linux'
        run: sudo chown -R $USER:$USER .ccache

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  # 3. Build Source Distribution
  build_sdist:
    name: Build source distribution
    needs: run_ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Download generated stubs
        uses: actions/download-artifact@v8
        with:
          name: py-stubs
          path: nnengine/

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  # 4. Final Publish
  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nn-engine-core
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1